// <auto-generated />
using JellyBellyWikiApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JellyBellyWikiApi.Migrations
{
    [DbContext(typeof(JellyBellyWikiApiContext))]
    [Migration("20231207044551_TempRemoveSeedData")]
    partial class TempRemoveSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JellyBellyWikiApi.Models.Bean", b =>
                {
                    b.Property<int>("BeanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorGroup")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FlavorName")
                        .HasColumnType("longtext");

                    b.Property<bool>("GlutenFree")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GroupNameSerialized")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredients")
                        .HasColumnType("longtext");

                    b.Property<bool>("Kosher")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Seasonal")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SugarFree")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BeanId");

                    b.ToTable("Beans");
                });

            modelBuilder.Entity("JellyBellyWikiApi.Models.Fact", b =>
                {
                    b.Property<int>("FactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("FactId");

                    b.ToTable("Facts");

                    b.HasData(
                        new
                        {
                            FactId = 1,
                            Description = "Jelly Belly beans gained national attention when they were featured in the White House during the 1980s. President Ronald Reagan was a big fan of Jelly Belly beans, and they became known as the 'President's candy.'.",
                            Title = "Presidential Favorite"
                        },
                        new
                        {
                            FactId = 2,
                            Description = "Jelly Belly is known for its extensive flavor selection, with over 100 different flavors available. Some of the more unusual flavors include Buttered Popcorn, Dr. Pepper, and even Harry Potter-themed flavors like Bertie Bott's Every Flavor Beans.",
                            Title = "Over 100 Flavors"
                        },
                        new
                        {
                            FactId = 3,
                            Description = "Jelly Belly beans have been used to create intricate pieces of art. Artists and enthusiasts have used the beans to make mosaics, portraits, and sculptures.",
                            Title = "Bean Art"
                        },
                        new
                        {
                            FactId = 4,
                            Description = "The Very Cherry flavor was one of the first flavors created by Jelly Belly, and it remains one of the most popular to this day.",
                            Title = "First Flavor"
                        },
                        new
                        {
                            FactId = 5,
                            Description = "Making Jelly Belly beans is a complex process. It involves several stages, including creating the flavor centers, adding the candy shell, and polishing the beans to achieve their signature shine.",
                            Title = "Behind the Scenes"
                        });
                });

            modelBuilder.Entity("JellyBellyWikiApi.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Combination")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Combination = "[\"Very Cherry \\u002B Very Cherry \\u002B Coconut \\u002B Buttered Popcorn \\u002B Cherry Turnover\"]",
                            Name = "Cherry Turnover"
                        },
                        new
                        {
                            RecipeId = 2,
                            Combination = "[\"Green Apple \\u002B Green Apple \\u002B Cinnamon \\u002B Apple Pie\"]",
                            Name = "Apple Pie"
                        },
                        new
                        {
                            RecipeId = 3,
                            Combination = "[\"Top Banana \\u002B Top Banana \\u002B Buttered Popcorn \\u002B Banana Bread\"]",
                            Name = "Banana Bread"
                        },
                        new
                        {
                            RecipeId = 4,
                            Combination = "[\"Top Banana \\u002B Cream Soda \\u002B Coconut \\u002B Banana Cream Pie\"]",
                            Name = "Banana Cream Pie"
                        },
                        new
                        {
                            RecipeId = 5,
                            Combination = "[\"Berry Blu \\u002B Sunkist Lemon \\u002B Berry Lemonade\"]",
                            Name = "Berry Lemonade"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
