// <auto-generated />
using JellyBellyWikiApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JellyBellyWikiApi.Migrations
{
    [DbContext(typeof(JellyBellyWikiApiContext))]
    [Migration("20231201083253_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("JellyBellyWikiApi.Models.Bean", b =>
                {
                    b.Property<int>("BeanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorGroup")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FlavorName")
                        .HasColumnType("longtext");

                    b.Property<bool>("GlutenFree")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GroupName")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Ingredients")
                        .HasColumnType("longtext");

                    b.Property<bool>("Kosher")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mixes")
                        .HasColumnType("longtext");

                    b.Property<bool>("Seasonal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Sku")
                        .HasColumnType("int");

                    b.Property<bool>("SugarFree")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BeanId");

                    b.ToTable("Beans");
                });
#pragma warning restore 612, 618
        }
    }
}
